# Generated by Django 3.2.6 on 2022-01-12 08:08

from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields
import mptt.fields
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('date_add_individual', models.DateField(auto_now=True, verbose_name='Дата добавление клиента')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'verbose_name_plural': 'Департамент',
            },
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=155, unique=True, verbose_name='Номер телефон')),
                ('extension_phone', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=155, unique=True), blank=True, null=True, size=None, verbose_name='Дополнительные номера')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('status', models.BooleanField(default=False, verbose_name='Статус')),
                ('change_status', models.DateTimeField(verbose_name='Дата изменения статуса')),
                ('email', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, null=True, size=None, verbose_name='Почта')),
                ('male', models.CharField(choices=[('1', 'мужской'), ('2', 'женский'), ('3', 'неизвестно')], max_length=12, verbose_name='Пол')),
                ('type', models.CharField(choices=[('1', 'первичный'), ('2', 'повторный'), ('3', 'внешний'), ('4', 'косвенный')], max_length=20, verbose_name='Тип')),
                ('timezone', timezone_field.fields.TimeZoneField(verbose_name='Часовой пояс')),
                ('vk', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None, verbose_name='В Контакте')),
                ('fb', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None, verbose_name='Facebook')),
                ('ok', models.URLField(blank=True, null=True, verbose_name='Одноклассники')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='Telegram')),
                ('whatsapp', models.CharField(blank=True, max_length=255, null=True, verbose_name='WhatsApp')),
                ('viber', models.URLField(blank=True, null=True, verbose_name='Viber')),
            ],
            options={
                'verbose_name_plural': 'Физическое лицо (Клиент)',
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_title', models.CharField(max_length=255, verbose_name='Полное название')),
                ('abbreviation', models.CharField(max_length=255, verbose_name='Сокращенное название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('inn', models.CharField(max_length=20, verbose_name='ИНН')),
                ('kpp', models.CharField(max_length=20, verbose_name='КПП')),
                ('department', models.ManyToManyField(blank=True, null=True, to='account.Department', verbose_name='Департамент')),
            ],
            options={
                'verbose_name_plural': 'Юридическое лицо',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='individual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='account.individual', verbose_name='Физическое лицо'),
        ),
        migrations.AddField(
            model_name='department',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='account.department'),
        ),
    ]
