# Generated by Django 3.2.6 on 2022-01-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='individual',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='department',
        ),
        migrations.AddField(
            model_name='department',
            name='individuals',
            field=models.ManyToManyField(blank=True, db_index=True, null=True, related_name='departments', to='account.Individual', verbose_name='Физические лица'),
        ),
        migrations.AddField(
            model_name='entity',
            name='departments',
            field=models.ManyToManyField(blank=True, null=True, to='account.Department', verbose_name='Департаменты'),
        ),
        migrations.AlterField(
            model_name='department',
            name='date_add_individual',
            field=models.DateField(blank=True, null=True, verbose_name='Дата добавление клиента'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='change_status',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения статуса'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения'),
        ),
    ]
