# Generated by Django 3.2.6 on 2022-01-12 13:18

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220112_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(),
        ),
    ]
