# Generated by Django 3.2.6 on 2022-01-12 13:38

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_individual_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(verbose_name='Часовой пояс'),
        ),
    ]
